export const defaultObject = [{
    type: 'Text',
    value: `Enter Text`,
    width: 50,
    height: 25,
    x: 0,
    y: 0,
    rotate: 0,
    radius: [0,0,0,0],
    differentRadius: false,
    zIndex: 1,
    bold: false,
    underline: false,
    italic: false,
    size: 12,
    textAlign: 'left',
    font: 'Ariel',
    textColor: [0,0,0,1],
    fillColor: [0,0,0,0],
    borderStyle: 'solid',
    borderWidth: 0.5,
    borderColor: [0,0,0,1],
},
{
    type: 'Square',
    width: 25,
    height: 25,
    x: 0,
    y: 0,
    rotate: 0,
    radius: [0,0,0,0],
    differentRadius: false,
    zIndex: 1,
    fillColor: [190,190,190,1],
    borderStyle: 'none',
    borderWidth: 0,
    borderColor: [0,0,0,1],
},
{
    type: 'Ellipse',
    width: 25,
    height: 25,
    x: 0,
    y: 0,
    rotate: 0,
    zIndex: 1,
    fillColor: [190,190,190,1],
    borderStyle: 'none',
    borderWidth: 0,
    borderColor: [0,0,0,1],
},
{
    height: 0,
    type: 'Line',
    width: 50,
    x: 0,
    y: 0,
    rotate: 0,
    zIndex: 1,
    borderStyle: 'solid',
    borderWidth: 2,
    borderColor: [0,0,0,1],
},
{
    type: 'Image',
    src: '',
    width: 25,
    height: 25,
    x: 0,
    y: 0,
    rotate: 0,
    radius: [0,0,0,0],
    differentRadius: false,
    zIndex: 1,
    borderStyle: 'none',
    borderWidth: 0,
    borderColor: [0,0,0,1],
},
{
    type: 'Icon',
    code: '',
    class: 'material-icons',
    width: 6,
    x: 0,
    y: 0,
    rotate: 0,
    radius: [0,0,0,0],
    differentRadius: false,
    zIndex: 1,
    borderStyle: 'none',
    borderWidth: 0,
    borderColor: [0,0,0,1],
    fillColor: [0,0,0,1],
},
]