export const defaultText = {
    type: 'Text',
    width: 50,
    height: 10,
    x: 0,
    y: 0,
    rotate: 0,
    radius: [0,0,0,0],
    differentRadius: false,
    zIndex: 1,
    bold: false,
    underline: false,
    italic: false,
    size: 12,
    textAlign: 'left',
    font: 'Ariel',
    textColor: [0,0,0,1],
    fillColor: [255,255,255,0],
    borderStyle: 'none',
    borderWidth: 0,
    borderColor: [0,0,0,1],
}

export const defaultSquare = {
    type: 'Square',
    width: 25,
    height: 25,
    x: 0,
    y: 0,
    rotate: 0,
    radius: [0,0,0,0],
    differentRadius: false,
    zIndex: 1,
    fillColor: [255,255,255,0],
    borderStyle: 'none',
    borderWidth: 0,
    borderColor: [0,0,0,1],
}

export const defaultEllipse = {
    type: 'Ellipse',
    width: 25,
    height: 25,
    x: 0,
    y: 0,
    rotate: 0,
    zIndex: 1,
    fillColor: [255,255,255,0],
    borderStyle: 'none',
    borderWidth: 0,
    borderColor: [0,0,0,1],
}

export const defaultLine = {
    type: 'Line',
    width: 25,
    x: 0,
    y: 0,
    rotate: 0,
    zIndex: 1,
    borderStyle: 'none',
    borderWidth: 0,
    borderColor: [0,0,0,1],
}